eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7010/eureka/
server:
  port: 8777
spring:
  application:
    name: ribbon-service

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  endpoint:
    health:
      show-details: always