server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7010/eureka/

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/liujx0804/Config
          search-paths: conf
          username: 你的git账号
          password: 你的git密码
      label: master
