server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7010/eureka/

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/liujx0804/Config
          search-paths: conf
          username: 2876564629@qq.com
          password: 7k8;_&fAHA6HT0
      label: master
